-- 테이블 및 컬럼 주석 추가 스크립트
-- 토론 플랫폼 데이터베이스 스키마 주석 추가

USE debate_db;

-- users 테이블 주석
ALTER TABLE users COMMENT = '사용자 정보 테이블';
ALTER TABLE users MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '사용자 ID';
ALTER TABLE users MODIFY COLUMN email VARCHAR(255) NOT NULL UNIQUE COMMENT '이메일 주소 (로그인 ID)';
ALTER TABLE users MODIFY COLUMN password VARCHAR(255) NOT NULL COMMENT '비밀번호 (BCrypt 해시)';
ALTER TABLE users MODIFY COLUMN nickname VARCHAR(50) NOT NULL COMMENT '닉네임';
ALTER TABLE users MODIFY COLUMN profile_image VARCHAR(500) COMMENT '프로필 이미지 URL';
ALTER TABLE users MODIFY COLUMN bio TEXT COMMENT '자기소개';
ALTER TABLE users MODIFY COLUMN status VARCHAR(255) NOT NULL COMMENT '사용자 상태 (ACTIVE: 활성, SUSPENDED: 정지, DELETED: 삭제)';
ALTER TABLE users MODIFY COLUMN email_verified BOOLEAN NOT NULL COMMENT '이메일 인증 여부';
ALTER TABLE users MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT '생성 일시';
ALTER TABLE users MODIFY COLUMN updated_at DATETIME(6) NOT NULL COMMENT '수정 일시';

-- debate 테이블 주석
ALTER TABLE debate COMMENT = '토론 주제 테이블';
ALTER TABLE debate MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '토론 ID';
ALTER TABLE debate MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '토론 작성자 ID';
ALTER TABLE debate MODIFY COLUMN category_id BIGINT NOT NULL COMMENT '카테고리 ID';
ALTER TABLE debate MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '토론 제목';
ALTER TABLE debate MODIFY COLUMN content TEXT NOT NULL COMMENT '토론 내용';
ALTER TABLE debate MODIFY COLUMN start_date DATETIME(6) NOT NULL COMMENT '토론 시작 일시';
ALTER TABLE debate MODIFY COLUMN end_date DATETIME(6) NOT NULL COMMENT '토론 종료 일시';
ALTER TABLE debate MODIFY COLUMN status VARCHAR(255) NOT NULL COMMENT '토론 상태 (SCHEDULED: 예정, ACTIVE: 진행중, ENDED: 종료)';
ALTER TABLE debate MODIFY COLUMN is_hidden BOOLEAN NOT NULL COMMENT '숨김 여부';
ALTER TABLE debate MODIFY COLUMN view_count INT NOT NULL COMMENT '조회수';
ALTER TABLE debate MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT '생성 일시';
ALTER TABLE debate MODIFY COLUMN updated_at DATETIME(6) NOT NULL COMMENT '수정 일시';

-- categories 테이블 주석
ALTER TABLE categories COMMENT = '카테고리 테이블';
ALTER TABLE categories MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '카테고리 ID';
ALTER TABLE categories MODIFY COLUMN name VARCHAR(100) NOT NULL UNIQUE COMMENT '카테고리명 (고유값)';
ALTER TABLE categories MODIFY COLUMN description TEXT COMMENT '카테고리 설명';
ALTER TABLE categories MODIFY COLUMN order_num INT COMMENT '정렬 순서';
ALTER TABLE categories MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT '생성 일시';
ALTER TABLE categories MODIFY COLUMN updated_at DATETIME(6) NOT NULL COMMENT '수정 일시';

-- comments 테이블 주석
ALTER TABLE comments COMMENT = '댓글 테이블';
ALTER TABLE comments MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '댓글 ID';
ALTER TABLE comments MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '댓글 작성자 ID';
ALTER TABLE comments MODIFY COLUMN debate_id BIGINT NOT NULL COMMENT '토론 ID';
ALTER TABLE comments MODIFY COLUMN parent_id BIGINT COMMENT '부모 댓글 ID (대댓글인 경우)';
ALTER TABLE comments MODIFY COLUMN content TEXT NOT NULL COMMENT '댓글 내용';
ALTER TABLE comments MODIFY COLUMN is_hidden BOOLEAN NOT NULL COMMENT '숨김 여부';
ALTER TABLE comments MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT '생성 일시';
ALTER TABLE comments MODIFY COLUMN updated_at DATETIME(6) NOT NULL COMMENT '수정 일시';

-- debate_opinion 테이블 주석
ALTER TABLE debate_opinion COMMENT = '토론 의견 테이블';
ALTER TABLE debate_opinion MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '의견 ID';
ALTER TABLE debate_opinion MODIFY COLUMN debate_id BIGINT NOT NULL COMMENT '토론 ID';
ALTER TABLE debate_opinion MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '사용자 ID';
ALTER TABLE debate_opinion MODIFY COLUMN side VARCHAR(20) NOT NULL COMMENT '입장 (FOR: 찬성, AGAINST: 반대, NEUTRAL: 중립, OTHER: 기타)';
ALTER TABLE debate_opinion MODIFY COLUMN content TEXT COMMENT '의견 내용';
ALTER TABLE debate_opinion MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT '생성 일시';
ALTER TABLE debate_opinion MODIFY COLUMN updated_at DATETIME(6) NOT NULL COMMENT '수정 일시';

-- bookmarks 테이블 주석
ALTER TABLE bookmarks COMMENT = '북마크 테이블';
ALTER TABLE bookmarks MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '북마크 ID';
ALTER TABLE bookmarks MODIFY COLUMN debate_id BIGINT NOT NULL COMMENT '토론 ID';
ALTER TABLE bookmarks MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '사용자 ID';
ALTER TABLE bookmarks MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT '생성 일시';

-- likes 테이블 주석
ALTER TABLE likes COMMENT = '좋아요 테이블';
ALTER TABLE likes MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '좋아요 ID';
ALTER TABLE likes MODIFY COLUMN debate_id BIGINT NOT NULL COMMENT '토론 ID';
ALTER TABLE likes MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '사용자 ID';
ALTER TABLE likes MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT '생성 일시';

-- reports 테이블 주석
ALTER TABLE reports COMMENT = '신고 테이블';
ALTER TABLE reports MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '신고 ID';
ALTER TABLE reports MODIFY COLUMN reporter_id BIGINT NOT NULL COMMENT '신고자 ID';
ALTER TABLE reports MODIFY COLUMN target_type VARCHAR(20) NOT NULL COMMENT '신고 대상 타입 (DEBATE: 토론, COMMENT: 댓글, USER: 사용자)';
ALTER TABLE reports MODIFY COLUMN target_id BIGINT NOT NULL COMMENT '신고 대상 ID';
ALTER TABLE reports MODIFY COLUMN reason VARCHAR(255) NOT NULL COMMENT '신고 사유';
ALTER TABLE reports MODIFY COLUMN description TEXT COMMENT '신고 상세 설명';
ALTER TABLE reports MODIFY COLUMN status VARCHAR(255) NOT NULL COMMENT '신고 처리 상태 (PENDING: 대기중, APPROVED: 승인, REJECTED: 거부)';
ALTER TABLE reports MODIFY COLUMN processed_by BIGINT COMMENT '처리한 관리자 ID';
ALTER TABLE reports MODIFY COLUMN processed_at DATETIME(6) COMMENT '처리 일시';
ALTER TABLE reports MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT '생성 일시';

-- chat_messages 테이블 주석
ALTER TABLE chat_messages COMMENT = '채팅 메시지 테이블';
ALTER TABLE chat_messages MODIFY COLUMN id BIGINT AUTO_INCREMENT COMMENT '채팅 메시지 ID';
ALTER TABLE chat_messages MODIFY COLUMN debate_id BIGINT NOT NULL COMMENT '토론 ID';
ALTER TABLE chat_messages MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '메시지 작성자 ID';
ALTER TABLE chat_messages MODIFY COLUMN message TEXT NOT NULL COMMENT '메시지 내용';
ALTER TABLE chat_messages MODIFY COLUMN created_at DATETIME(6) NOT NULL COMMENT '생성 일시';


